name: Website on GitHub pages
on: [push, workflow_dispatch]
permissions:
  contents: write
  id-token: write # This is required for requesting the JWT
jobs:
  ssg:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Make
        run: |
          ./generate-scripts/get-ssg.sh
          
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: bins
          path: ssg
          
  lowdown:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Make
        run: |
          ./generate-scripts/get-lowdown.sh
          
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: bins
          path: lowdown/lowdown
          
  generate-website:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    needs: [ssg, lowdown]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: bins
          
      - name: Generate site
        env:
          SOURCE_FOLDER: .
          AWK_FOLDER: awk-scripts
          SSG_TITLE: S.S. Law
          SSG_BASE_URL: https://syndamia.gitlab.io/ss-law/
        run: |
          chmod +x lowdown ssg
          mv ./lowdown /usr/local/bin/
          ./generate-scripts/generate-site.sh
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: website
          path: public

  deploy-github-pages:
    needs: generate-website
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: gh-pages
          
      - name: Clear old contents
        run: |
          rm -rf * .github .gitlab-ci.yml .ssgignore 
        
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: website
        
      - name: GitHub Pages
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Generated by ${GITHUB_RUN_NUMBER}@${GITHUB_RUN_ID}" || true 
          git push
